import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AgenticProvider } from "@agentic-zero/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Agentic Web App",
    description: "Generated by create-agentic-app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AgenticProvider config={{
                    autoStart: false,
                    debug: process.env.NODE_ENV === 'development'
                }}>
                    {children}
                </AgenticProvider>
            </body>
        </html>
    );
}
