"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const core_1 = require("@agentic-web/core");
const inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "Agentic Web App",
    description: "Generated by create-agentic-app",
};
function RootLayout({ children, }) {
    return (<html lang="en">
            <body className={inter.className}>
                <core_1.AgenticProvider config={{
            autoStart: false,
            debug: process.env.NODE_ENV === 'development'
        }}>
                    {children}
                </core_1.AgenticProvider>
            </body>
        </html>);
}
